name: mibisegmentation
channels:
  - conda-forge
dependencies:
  - python =3.10.0
  - tifffile
  - typer
  - xarray
  - rasterio
  - scikit-image
  - geopandas
  - git
  - gcc
  - pip
  - pip:
    - tensorflow-cpu
    - deepcell
    - git+https://github.com/WEHI-SODA-Hub/MibiSegmentation.git
